version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci
    labels: [dependencies]
    open-pull-requests-limit: 1
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: build
    labels: [dependencies]
    open-pull-requests-limit: 1
    groups:
      submodules:
        patterns: ["*"]

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: build
    labels: [dependencies]
